### ISSUE TITLE
Include ❤, 🎉 and 🚀 for scoring proposals

### ISSUE THREAD

**Issue by aXu-AP** [godot-proposals-viewer/godot-proposals-viewer.github.io#21]
Often people react with ❤, 🎉 or 🚀 to proposals, each of which imply supporting it (maybe with a bit more enthusiasm than 👍 even). Maybe the proposals viewer could count these as 👍 as well? It would of course make the system more complex, since you need to take into account that one user might react multiple times to a post.
There's also 👀 and 😀, but they're more ambiguous, I wouldn't count them.

And yes, I have an issue that has only 🎉 reactions to it but that's besides the point 🤣

**Comment by Calinou** [comment]
The reason I don't include those reactions is that it would result in specific users being counted more than once, as a user would then be able to leave several "positive" reactions on a single post.

The GitHub REST API doesn't return *which* people have reacted to a post – it only reacts the number of reactions of each type. It's possible that the GraphQL API doesn't have this limitation, but using this API requires rewriting the fetching script from scratch.

**Comment by aXu-AP** [comment]
Yeah I was pondering if the API would tell who reacted, but since not, it won't be worth the effort. For the more popular proposals it likely averages out anyway.

**Comment by Calinou** [comment]
Closing per the above comments.
