### ISSUE TITLE
Proposals out of date

### ISSUE THREAD

**Issue by dbnicholson** [godot-proposals-viewer/godot-proposals-viewer.github.io#26]
I was looking for my [proposal](https://github.com/godotengine/godot-proposals/issues/10986) in the viewer and it wasn't showing up. It looks like the [Continuous Integration workflow](https://github.com/godot-proposals-viewer/godot-proposals-viewer.github.io/actions/workflows/ci.yml) is disabled since there haven't been any changes to the repo for a while. Could you re-enable it and run it again?

**Comment by Calinou** [comment]
Done.

This happens if 60 days pass without any commits made to this repository (not godot-proposals). If you know of a workaround for this, let me know :slightly_smiling_face:

**Comment by dbnicholson** [comment]
Here's some workaround ideas:

* Actually commit `proposals.json` to the repo. The commit history would be really ugly, though.
* Make an automated release of this repo every 59 days. Even if the code hasn't changed, you can still just add another tag.
* Use a separate workflow that just creates and uploads `proposals.json` as an artifact and then pull that into the pages workflow instead of building it there. I'm not sure if this would count as activity, though.
* Use a scheduled workflow from the godot-proposals repo that triggers this workflow from a [repository_dispatch event](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#repository_dispatch). If the godot-proposals repo ever went inactive for 60 days, then that would mean there would be nothing for the viewer to update, anyways.
* Move the viewer into the godot-proposals repo and just leave behind a redirect here. Same comment about the proposals going inactive. I think this would be the best, and I imagine that you have the privileges to do that kind of change.
